# Generated by Django 4.2.5 on 2023-10-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos', models.CharField(max_length=30)),
                ('camada', models.IntegerField()),
            ],
        ),
    ]
